version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: trpc_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: trpc
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trpc
    ports:
      - "5432:5432"
    volumes:
      - ./database-data/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trpc"]
      interval: 10s
      timeout: 5s
      retries: 5
